# Flutter build
# variables:
#   projectDirectory: 'covid_19_tracker'
trigger:
- set_pipeline_for_tests
jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    steps:
    # - task: FlutterInstall@0
    #   inputs:
    #     channel: 'stable'
    #     version: '3.0.1'

    - script: pipelines/fscripts.sh install_flutter
      displayName: Install Flutter

    # - task: FlutterBuild@0
    #   inputs:
    #     target: apk
        # projectDirectory: $(projectDirectory)
    - script: pipelines/fscripts.sh build_app
      displayName: Build Flutter App
    
    - script: pipelines/fscripts.sh launch_avd
      displayName: Launch AVD

    - script: pipelines/fscripts.sh flutter_integration_test 
      displayName: 'Run integration tests'
  
    # - task: AndroidSigning@3
    #   displayName: 'Signing and aligning APK file(s) **/*.apk'
    #   inputs:
    #     apkFiles: '**/*.apk'
    #     apksign: true
    #     apksignerKeystoreFile: key.jks
    #     apksignerKeystorePassword: $(keypassword)
    #     apksignerKeystoreAlias: $(key)
    #     apksignerKeyPassword: $(keypassword)
    # - task: CopyFiles@2
    #   inputs:
    #     contents: '**/*.apk'
    #     targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1